### ISSUE TITLE
PolyU data set should be listed under benchmarks 

### ISSUE THREAD

**Issue by TouqeerAhmad** [flyywh/Image-Denoising-State-of-the-art#6]
Link for the arxiv:
https://arxiv.org/pdf/1804.02603.pdf

Link to the data set:
https://github.com/csjunxu/PolyU-Real-World-Noisy-Images-Dataset

Also another paper targeting real-world image denoising:

https://arxiv.org/pdf/1807.04686.pdf
https://github.com/GuoShi28/CBDNet

**Comment by flyywh** [comment]
Dear TouqeerAhmad,

I have updated the website.

If you do not mind, I hope to know your information so that I can say thanks on the website.

Best,

Wenhan

 
From: TouqeerAhmad
Date: 2018-08-02 07:04
To: flyywh/Image-Denoising-State-of-the-art
CC: Subscribed
Subject: [flyywh/Image-Denoising-State-of-the-art] PolyU data set should be listed under benchmarks (#6)
Link for the arxiv:
https://arxiv.org/pdf/1804.02603.pdf
Link to the data set:
https://github.com/csjunxu/PolyU-Real-World-Noisy-Images-Dataset
Also another paper targeting real-world image denoising:
https://arxiv.org/pdf/1807.04686.pdf
https://github.com/GuoShi28/CBDNet
